### ISSUE TITLE
Collisions of boxes since `coords` removed

### ISSUE THREAD

**Issue by harrelfe** [adayim/consort#11]
WIth `consort_plot` I used to be able to avoid collisions of boxes by specifying `coords`.  With the removal of that argument I'm getting collisions.  An example with output is here: http://hbiostat.org/rflow/doverview.html#fig-doverview-consort

Thanks
Frank

**Comment by adayim** [comment]
Hi Frank,

Thank you for reporting this. I will fix it and thank you for advocating this package.

**Comment by adayim** [comment]
Hi Frank,

It has been fixed now. You can also use the following with Quarto to produce Graphviz directly:
````markdown
```{r}
cat(build_grviz(g), file = "consort.gv")
```

```{dot}
//| label: consort-diagram
//| fig-cap: "CONSORT diagram of study XXX"
//| file: consort.gv
```
````

Or use the following to produce a nice SVG figure with `DiagrammeR`:
```r
plot(g, grViz = TRUE)
```
