### ISSUE TITLE
make comma separators useable for n values

### ISSUE THREAD

**Issue by AndrewNute** [adayim/consort#18]
I have a consort diagram which has > 100,000 patients after each exclusion step.  There is no way to format the numbers for "n = " so that there is a comma separator after each group of 3 digits.  So, my consort diagram's n values are not very reader friendly.

**Comment by adayim** [comment]
Sorry for the delay and thank you for reporting this. I have changed it defaults big number formatting. Would you be able to check it now? You need to install it from GitHub. Thank you very much.

**Comment by AndrewNute** [comment]
Finally tested this.  This seems to be working for all boxes except the first box corresponding to the first listed item in the orders statement of the consort_plot function.

**Comment by AndrewNute** [comment]
Any idea why the top box still doesn't work?

**Comment by adayim** [comment]
Sorry for taking so long. I forgot about this. I think it is fixed now. Can you have a try and let me know if it works? Thank you.

**Comment by dnolter** [comment]
This works now! Thanks for making this package.

**Comment by AndrewNute** [comment]
Awesome!
