### ISSUE TITLE
Factor variables for allocation

### ISSUE THREAD

**Issue by jackahall** [adayim/consort#20]
Currently, it seems that the `allocation` variable in `consort_plot` must be a character, but we usually code these variables as factors. It can be converted first using `as.character`, but this loses the ordering of the variable.

**Comment by adayim** [comment]
Thank you for pointing this out, I will fix this.

**Comment by adayim** [comment]
Hi, sorry. I don't think I can replicate this. Can you give me an example so I can test this?
