### ISSUE TITLE
Starting the consort diagram with multiple boxes

### ISSUE THREAD

**Issue by abduazizR** [adayim/consort#5]
Hi,

First of all, I would like to thank you so much for the package. This is exactly what I was looking for. I just have a question about building a consort diagram that starts with multiple boxes at the top. Something like shown in the image below
![image](https://user-images.githubusercontent.com/61837330/203578885-aba52416-e720-4cd8-88d9-5a35ab649f66.png)

Thanks.

**Comment by adayim** [comment]
Hi, thank you for interested in the package. It is a good suggestion, I will work on that. But I am quite busy currently, this may take a while.

**Comment by adayim** [comment]
You should be able to start consort diagram with multiple nodes now. It's already on the CRAN, please have a try.
