### ISSUE TITLE
Vignette file name misspelled

### ISSUE THREAD

**Issue by JonasEngstrom** [adayim/consort#8]
The file name `consrot_diagram.Rmd` should probably be spelled `consort_diagram.Rmd` in the vignettes folder.

**Comment by adayim** [comment]
Yes, I found out after I submitted the package. But thank you very much.

**Comment by JonasEngstrom** [comment]
No problem! I just found your package and I am playing around with it in R Studio right now. It’s really easy to use. Thank you for making it 😊
